export const ats = [
	"inurl:lever.co",
  'inurl:workable.com "United States"',
  'inurl:greenhouse.io -intitle:"jobs at"',
  "inurl:jobvite.com",
  "inurl:recruiterbox.com",
  "inurl:angel.co/company inurl:/jobs",
  // "inurl:linkedin.com/jobs/view/",
  "inurl:nodesk.co/remote-jobs",
  "inurl:recruitee.com/o",
  "inurl:breezy.hr/p/",
//  "inurl:icims.com/jobs",
  "inurl:workatastartup.com/jobs/",
  "inurl:stackoverflow.com/jobs/",
  "inurl:jobs.github.com/position/",
  // "inurl:taleo.net/careersection/+inurl:jobdetail.ftl",
  "inurl:jobs.us.pwc.com/job/",
  "inurl:jobs.smartrecruiters.com/",
  "inurl:careers.jobscore.com/careers/+inurl:/jobs/",
  "inurl:jobs.gohire.io/",
  "inurl:join.com/jobs/",
	"inurl:jobs.ashbyhq.com",
];
